window.env = {
  "MANPATH": "/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/opt/homebrew/share/man::",
  "TERM_PROGRAM": "vscode",
  "NODE": "/usr/local/bin/node",
  "INIT_CWD": "/Users/hunterhundley/UT Bootcamp Files/Hunter_",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "TMPDIR": "/var/folders/zh/b16hhqvj1d701x4p2q5q46240000gn/T/",
  "HOMEBREW_REPOSITORY": "/opt/homebrew",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_global_prefix": "/usr/local",
  "TERM_PROGRAM_VERSION": "1.85.1",
  "MallocNanoZone": "0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "ZDOTDIR": "/Users/hunterhundley",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "npm_config_local_prefix": "/Users/hunterhundley/UT Bootcamp Files/Hunter_",
  "USER": "hunterhundley",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.Sm6CUXU8MU/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "PATH": "/Users/hunterhundley/UT Bootcamp Files/Hunter_/node_modules/.bin:/Users/hunterhundley/UT Bootcamp Files/node_modules/.bin:/Users/hunterhundley/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/hunterhundley/UT Bootcamp Files/Hunter_/node_modules/.bin:/Users/hunterhundley/UT Bootcamp Files/node_modules/.bin:/Users/hunterhundley/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin",
  "_": "/Users/hunterhundley/UT Bootcamp Files/Hunter_/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/hunterhundley/UT Bootcamp Files/Hunter_/package.json",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "USER_ZDOTDIR": "/Users/hunterhundley",
  "npm_config_init_module": "/Users/hunterhundley/.npm-init.js",
  "npm_config_userconfig": "/Users/hunterhundley/.npmrc",
  "PWD": "/Users/hunterhundley/UT Bootcamp Files/Hunter_",
  "npm_command": "run-script",
  "EDITOR": "vi",
  "npm_lifecycle_event": "build",
  "LANG": "en_US.UTF-8",
  "npm_package_name": "portfolio",
  "XPC_FLAGS": "0x0",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "VSCODE_INJECTION": "1",
  "HOME": "/Users/hunterhundley",
  "SHLVL": "3",
  "VSCODE_GIT_ASKPASS_MAIN": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "HOMEBREW_PREFIX": "/opt/homebrew",
  "LOGNAME": "hunterhundley",
  "npm_config_cache": "/Users/hunterhundley/.npm",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/zh/b16hhqvj1d701x4p2q5q46240000gn/T/vscode-git-8ac843d6bb.sock",
  "npm_config_user_agent": "npm/8.11.0 node/v16.16.0 darwin arm64 workspaces/false",
  "HOMEBREW_CELLAR": "/opt/homebrew/Cellar",
  "INFOPATH": "/opt/homebrew/share/info:/opt/homebrew/share/info:",
  "GIT_ASKPASS": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)",
  "COLORTERM": "truecolor",
  "npm_config_prefix": "/usr/local",
  "npm_node_execpath": "/usr/local/bin/node",
  "SERVICE_ID": "service_8iek2zr",
  "TEMPLATE_ID": "template_hbzjwh7",
  "PUBLIC_KEY": "juroUeYqFqyKEL-IM"
};